"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import config
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-q3q%ibng@ptw9mul+7cb!4qfqg8ocu(nhbbct&**p-st%-#!2n')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

# Домен фронтенда, обращающегося к API. В разработке дополнительно разрешены
# локальные адреса типовых dev-серверов (Vite/CRA/Next), чтобы фронтенд-команда
# могла работать против локального или прод-бэкенда без правки .env на время разработки.
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='https://lorssy.com,https://www.lorssy.com',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)
if DEBUG:
    CORS_ALLOWED_ORIGINS += [
        'http://localhost:3000', 'http://127.0.0.1:3000',
        'http://localhost:5173', 'http://127.0.0.1:5173',
    ]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'lors',
    'assistant',
]

TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='')

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'LORS API',
    'DESCRIPTION': 'Каталог лекал автоковриков LORS SYRIA',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

UNFOLD = {
    'SITE_TITLE': 'LORS admin',
    'SITE_HEADER': 'LORS',
    'DASHBOARD_CALLBACK': 'lors.dashboard.dashboard_callback',
    'SIDEBAR': {
        'show_all_applications': False,
        'navigation': [
            {
                'title': 'Каталог',
                'items': [
                    {
                        'title': 'Марки',
                        'icon': 'sell',
                        'link': reverse_lazy('admin:lors_brand_changelist'),
                    },
                    {
                        'title': 'Модели автомобилей',
                        'icon': 'directions_car',
                        'link': reverse_lazy('admin:lors_carmodel_changelist'),
                    },
                    {
                        'title': 'Ценовые категории',
                        'icon': 'sell',
                        'link': reverse_lazy('admin:lors_pricecategory_changelist'),
                    },
                    {
                        'title': 'Материалы',
                        'icon': 'layers',
                        'link': reverse_lazy('admin:lors_material_changelist'),
                    },
                    {
                        'title': 'Цвета',
                        'icon': 'palette',
                        'link': reverse_lazy('admin:lors_color_changelist'),
                    },
                ],
            },
            {
                'title': 'Товары',
                'items': [
                    {
                        'title': 'Категории товаров',
                        'icon': 'category',
                        'link': reverse_lazy('admin:lors_productcategory_changelist'),
                    },
                    {
                        'title': 'Товары',
                        'icon': 'inventory_2',
                        'link': reverse_lazy('admin:lors_product_changelist'),
                    },
                ],
            },
            {
                'title': 'Контент',
                'items': [
                    {
                        'title': 'Страницы',
                        'icon': 'article',
                        'link': reverse_lazy('admin:lors_page_changelist'),
                    },
                    {
                        'title': 'Настройки сайта',
                        'icon': 'settings',
                        'link': reverse_lazy('admin:lors_sitesettings_changelist'),
                    },
                ],
            },
            {
                'title': 'Обращения',
                'items': [
                    {
                        'title': 'Заявки',
                        'icon': 'report',
                        'link': reverse_lazy('admin:lors_lead_changelist'),
                    },
                    {
                        'title': 'Отзывы',
                        'icon': 'rate_review',
                        'link': reverse_lazy('admin:lors_review_changelist'),
                    },
                ],
            },
            {
                'title': 'Система',
                'items': [
                    {
                        'title': 'Пользователи',
                        'icon': 'person',
                        'link': reverse_lazy('admin:auth_user_changelist'),
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='lors'),
        'USER': config('DB_USER', default='lors_user'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
