# Generated by Django 6.0.6 on 2026-07-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], max_length=20)),
                ('external_user_id', models.CharField(max_length=100, verbose_name='id пользователя в канале')),
                ('direction', models.CharField(choices=[('in', 'от клиента'), ('out', 'от бота')], max_length=3)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'сообщение бота',
                'verbose_name_plural': 'сообщения бота',
                'ordering': ['-created_at'],
            },
        ),
    ]
