# Generated by Django 6.0.8 on 2026-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('claude', 'Claude (Anthropic)'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], default='claude', max_length=20, verbose_name='провайдер ИИ')),
            ],
            options={
                'verbose_name': 'настройки ассистента',
                'verbose_name_plural': 'настройки ассистента',
            },
        ),
    ]
