# Generated by Django 6.0.6 on 2026-07-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_code', models.CharField(blank=True, max_length=50, verbose_name='код шаблона')),
                ('car_type', models.CharField(blank=True, max_length=255, verbose_name='тип автомобиля')),
                ('driver_cut', models.CharField(blank=True, max_length=255, verbose_name='шофёр')),
                ('package', models.CharField(blank=True, max_length=255, verbose_name='пакет')),
                ('second_row_package', models.CharField(blank=True, max_length=255, verbose_name='пакет 2-й ряд')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='ссылка на видео')),
                ('sheet_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='строка в исходной таблице')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='lors.brand')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
