# Generated by Django 6.0.6 on 2026-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='sheet_row',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='строка в исходной таблице'),
        ),
    ]
