# Generated by Django 6.0.6 on 2026-07-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0003_complaint_complaintphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='долгота')),
                ('about', models.TextField(blank=True, verbose_name='о компании')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'настройки сайта',
                'verbose_name_plural': 'настройки сайта',
            },
        ),
    ]
