# Generated by Django 6.0.6 on 2026-07-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0004_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('text', models.TextField(verbose_name='текст отзыва')),
                ('photo', models.ImageField(blank=True, upload_to='reviews/%Y/%m/', verbose_name='фото')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
