# Generated by Django 6.0.6 on 2026-07-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0005_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'марка', 'verbose_name_plural': 'марки'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['brand__name', 'name'], 'verbose_name': 'модель автомобиля', 'verbose_name_plural': 'модели автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'жалоба', 'verbose_name_plural': 'жалобы'},
        ),
        migrations.AlterModelOptions(
            name='complaintphoto',
            options={'verbose_name': 'фото жалобы', 'verbose_name_plural': 'фото жалобы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
