# Generated by Django 6.0.6 on 2026-07-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0006_alter_brand_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_type',
            field=models.CharField(blank=True, choices=[('تكسي عادي', 'تكسي عادي'), ('خمس أبواب (هاش باك)', 'خمس أبواب (هاش باك)'), ('ثلاث أبواب (هاش باك)', 'ثلاث أبواب (هاش باك)'), ('بابين (كوبي)', 'بابين (كوبي)'), ('كوبي بابين', 'كوبي بابين'), ('اربع ابواب (كوبي)', 'اربع ابواب (كوبي)'), ('بيك آب', 'بيك آب'), ('باكاج طويل', 'باكاج طويل')], max_length=255, verbose_name='тип автомобиля'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='driver_cut',
            field=models.CharField(blank=True, choices=[('دعسة مقصوصة', 'دعسة مقصوصة'), ('دعسة من تحت', 'دعسة من تحت'), ('بدون دعسة', 'بدون دعسة'), ('3D', '3D')], max_length=255, verbose_name='шофёр'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='package',
            field=models.CharField(blank=True, choices=[('قطعة واحدة', 'قطعة واحدة'), ('2 قطع', '2 قطع'), ('3 قطع', '3 قطع'), ('أربع قطع', 'أربع قطع'), ('لايوجد باكاج', 'لايوجد باكاج')], max_length=255, verbose_name='пакет'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='second_row_package',
            field=models.CharField(blank=True, choices=[('قطعة واحدة', 'قطعة واحدة'), ('2 قطع', '2 قطع'), ('3 قطع', '3 قطع'), ('قطعة واحدة + 3 قطع', 'قطعة واحدة + 3 قطع')], max_length=255, verbose_name='пакет 2-й ряд'),
        ),
    ]
