# Generated by Django 6.0.6 on 2026-07-13 08:16
"""
car_type/package became strict single-choice dropdowns (see CarModel.CAR_TYPE_CHOICES /
PACKAGE_CHOICES in 0007). A handful of rows imported from the source sheet had several
comma-separated values crammed into one cell (e.g. "тكسي عادي, خمس أبواب (هاش باك)") —
this keeps just the first value for those rows so they match the new choices.
"""

from django.db import migrations

NORMALIZED_FIELDS = ['car_type', 'package']


def normalize(apps, schema_editor):
    CarModel = apps.get_model('lors', 'CarModel')
    for field in NORMALIZED_FIELDS:
        for obj in CarModel.objects.exclude(**{field: ''}).filter(**{f'{field}__contains': ','}):
            first_value = getattr(obj, field).split(',')[0].strip()
            setattr(obj, field, first_value)
            obj.save(update_fields=[field])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0007_alter_carmodel_car_type_alter_carmodel_driver_cut_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize, noop),
    ]
