# Generated by Django 6.0.6 on 2026-07-28 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0008_normalize_combo_choice_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='telegram_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='whatsapp_url',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Телефон'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='тип')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='подпись')),
                ('value', models.CharField(max_length=255, verbose_name='значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='lors.sitesettings')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
                'ordering': ['contact_type', 'order', 'id'],
            },
        ),
    ]
