# Generated by Django 6.0.6 on 2026-07-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0009_remove_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('phone', 'Телефон'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook')], max_length=20, verbose_name='тип'),
        ),
    ]
