# Generated by Django 6.0.6 on 2026-07-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0010_alter_contact_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='слаг')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('body', models.TextField(blank=True, verbose_name='текст')),
                ('image', models.ImageField(blank=True, upload_to='pages/%Y/%m/', verbose_name='изображение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы',
                'ordering': ['slug'],
            },
        ),
    ]
