# Generated by Django 6.0.6
"""
Заготовки контентных страниц под будущий фронтенд (по образцу турецкого сайта
lorsotopaspas.com: Hakkımızda/Franchise/Üretim süreci/Malzeme rehberi) —
фронтенд может сразу обращаться по известным slug, текст заполняется
позже через /admin/.
"""

from django.db import migrations

PAGES = [
    ('about', 'من نحن'),
    ('franchise', 'الامتياز التجاري'),
    ('production', 'عملية الإنتاج'),
    ('materials', 'دليل المواد'),
]


def seed(apps, schema_editor):
    Page = apps.get_model('lors', 'Page')
    for slug, title in PAGES:
        Page.objects.get_or_create(slug=slug, defaults={'title': title})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0011_page'),
    ]

    operations = [
        migrations.RunPython(seed, noop),
    ]
