# Generated by Django 6.0.6
"""
Заготовка материалов по образцу турецкого сайта lorsotopaspas.com
(EVA yerli/EVA ithal/Halı 10mm/Halı 20mm) — цены на каждый добавляются
по моделям авто через инлайн на карточке CarModel в /admin/.
"""

from django.db import migrations

MATERIALS = [
    'EVA محلي',
    'EVA مستورد',
    'سجاد 10 مم',
    'سجاد 20 مم',
]


def seed(apps, schema_editor):
    Material = apps.get_model('lors', 'Material')
    for order, name in enumerate(MATERIALS):
        Material.objects.get_or_create(name=name, defaults={'order': order})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0013_color_material_matsetprice'),
    ]

    operations = [
        migrations.RunPython(seed, noop),
    ]
