# Generated by Django 6.0.6
"""
Complaint -> Lead: единая точка входа для всех обращений клиента (жалоба /
заказ коврика из конфигуратора / заказ товара), а не только рекламаций.
Написано вручную через RenameModel/RenameField, чтобы сохранить существующие
записи (autodetector в неинтерактивном режиме предлагал drop+create).
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0015_productcategory_product_productvariant'),
    ]

    operations = [
        migrations.RenameModel(old_name='Complaint', new_name='Lead'),
        migrations.RenameModel(old_name='ComplaintPhoto', new_name='LeadPhoto'),
        migrations.RenameField(model_name='leadphoto', old_name='complaint', new_name='lead'),
        migrations.AlterField(
            model_name='leadphoto',
            name='image',
            field=models.ImageField(upload_to='leads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='car_model',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='leads', to='lors.carmodel',
            ),
        ),
        migrations.AlterField(
            model_name='lead',
            name='text',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(
                choices=[
                    ('complaint', 'жалоба'),
                    ('mat_order', 'заказ коврика'),
                    ('product_order', 'заказ товара'),
                ],
                default='complaint', max_length=20, verbose_name='тип заявки',
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='material',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='leads', to='lors.material',
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='mat_color',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='mat_color_leads', to='lors.color',
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='border_color',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='border_color_leads', to='lors.color',
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='heel_color',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='heel_color_leads', to='lors.color',
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_variant',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='leads', to='lors.productvariant',
            ),
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
        migrations.AlterModelOptions(
            name='leadphoto',
            options={'verbose_name': 'фото заявки', 'verbose_name_plural': 'фото заявки'},
        ),
    ]
