# Generated by Django 6.0.6 on 2026-07-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0016_rename_complaint_to_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='рейтинг'),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('site', 'сайт'), ('google', 'Google')], default='site', max_length=20, verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('phone', 'Телефон'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('youtube', 'YouTube')], max_length=20, verbose_name='тип'),
        ),
    ]
