# Generated by Django 6.0.6 on 2026-08-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0017_review_rating_review_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('phone', 'Телефон'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter')], max_length=20, verbose_name='тип'),
        ),
    ]
