# Generated by Django 6.0.6 on 2026-08-05 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0018_alter_contact_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'ценовая категория',
                'verbose_name_plural': 'ценовые категории',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_models', to='lors.pricecategory'),
        ),
        migrations.DeleteModel(
            name='MatSetPrice',
        ),
    ]
