# Generated by Django 6.0.6
"""
Реальные ценовые категории из прайс-листа компании («مقرر أسعار شركة لورس»):
каждая строка документа — своя категория с одной ценой, без искусственного
объединения «с пакетом»/«без пакета» в одну запись (в файле это разные суммы
для разных сочетаний, не всегда пара 1:1 — например, «7 мест» без пакета
дана двумя разными ценами, а «американец» с пакетом — двумя разными
категориями).

Привязка конкретных CarModel к нужной категории — вручную в /admin/,
это реальная бизнес-классификация, не автоматизируется.
"""

from django.db import migrations

CATEGORIES = [
    ('Седан, 5 мест (с пакетом)', 120),
    ('Джип, 5 мест (с пакетом)', 130),
    ('7 мест (с пакетом)', 140),
    ('7 мест, бизнес (с пакетом)', 150),
    ('Американец — Cadillac, GMC и т.п. (с пакетом)', 150),
    ('Carnival + Staria + H1 (с пакетом)', 170),
    ('Американец в целом + Land Cruiser (с пакетом)', 150),
    ('Седан (без пакета)', 90),
    ('Джип (без пакета)', 100),
    ('7 мест, без 7-го ряда (без пакета)', 110),
    ('7 мест, с 7-м рядом (без пакета)', 120),
    ('Бизнес (без пакета)', 130),
]


def seed(apps, schema_editor):
    PriceCategory = apps.get_model('lors', 'PriceCategory')
    for order, (name, price) in enumerate(CATEGORIES):
        PriceCategory.objects.get_or_create(name=name, defaults={'price': price, 'order': order})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0019_pricecategory_carmodel_price_category_and_more'),
    ]

    operations = [
        migrations.RunPython(seed, noop),
    ]
