# Generated by Django 6.0.6 on 2026-08-05 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0020_seed_price_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'вариант дэсе',
                'verbose_name_plural': 'варианты дэсе',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LogoOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'вариант логотипа',
                'verbose_name_plural': 'варианты логотипа',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.DecimalField(decimal_places=2, default=35, max_digits=10, verbose_name='цена добавления пакета')),
            ],
            options={
                'verbose_name': 'настройки цен',
                'verbose_name_plural': 'настройки цен',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='has_package',
            field=models.BooleanField(default=False, verbose_name='добавить пакет'),
        ),
        migrations.AddField(
            model_name='lead',
            name='dese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='lors.deseoption'),
        ),
        migrations.AddField(
            model_name='lead',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='lors.logooption'),
        ),
    ]
