# Generated by Django 6.0.6
"""
Наценки из прайс-листа компании: логотип (обычный/королевский) и дэсе
(тип 1/тип 2) — выбираются клиентом при заказе поверх базовой цены категории.
"""

from django.db import migrations

LOGO_OPTIONS = [
    ('Обычный', 3),
    ('Королевский', 6),
]

DESE_OPTIONS = [
    ('Тип 1', 15),
    ('Тип 2', 10),
]


def seed(apps, schema_editor):
    LogoOption = apps.get_model('lors', 'LogoOption')
    DeseOption = apps.get_model('lors', 'DeseOption')
    PricingSettings = apps.get_model('lors', 'PricingSettings')

    for order, (name, price) in enumerate(LOGO_OPTIONS):
        LogoOption.objects.get_or_create(name=name, defaults={'price': price, 'order': order})
    for order, (name, price) in enumerate(DESE_OPTIONS):
        DeseOption.objects.get_or_create(name=name, defaults={'price': price, 'order': order})
    PricingSettings.objects.get_or_create(pk=1, defaults={'package_price': 35})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0021_deseoption_logooption_pricingsettings_and_more'),
    ]

    operations = [
        migrations.RunPython(seed, noop),
    ]
