# Generated by Django 6.0.6 on 2026-08-13 11:55
"""
Две независимые правки объединены в одну миграцию, т.к. между ними нет
зависимости по данным:

1. CarModel.base_model/body_variant/year_from/year_to — под пошаговый выбор
   Марка→Модель→Кузов→Год в калькуляторе коврика на lorssy-frontend.
   Заполняются отдельной командой `parse_car_models` (авторазбор из name),
   не этой миграцией.

2. Lead.has_package/dese + модели DeseOption/PricingSettings — убраны:
   подтверждено (повторно), что в бизнесе нет платной опции «добавить
   пакет» и нет отдельной платной опции «дэсе» — это не то же самое, что
   CarModel.package/driver_cut (реальные свойства конкретной модели в
   каталоге, остаются как есть). LogoOption/Логотип — реальная опция,
   не тронута.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0022_seed_pricing_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='dese',
        ),
        migrations.DeleteModel(
            name='PricingSettings',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='has_package',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='base_model',
            field=models.CharField(blank=True, max_length=255, verbose_name='базовая модель'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='body_variant',
            field=models.CharField(blank=True, max_length=100, verbose_name='вариант кузова (из названия)'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год от'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год до'),
        ),
        migrations.DeleteModel(
            name='DeseOption',
        ),
    ]
