# Generated by Django 6.0.6
"""
Заглушка-плейсхолдер под первый товар вне калькулятора коврика: органайзер
багажника «LORS Deluxe» (طقم منظم صندوق LORS ديلوكس, $45, коричневый/
чёрный) — по фото/цене, которые прислал заказчик. Намеренно не связан с
калькулятором коврика (Lead.car_model/material/...) — отдельная линейка
товаров, заказ через product_variant (TYPE_PRODUCT_ORDER), см. Lead в
models.py.

На проде на момент применения этой миграции уже оказались заведены — сами,
через /admin/ — 2 реальных товара с этим именем (по цвету), в каждом по 3
варианта размера (30/40/60 см, $45/$50/$55, с настоящими фото) — то есть
Product.name не уникальное поле, и это осознанно (2 отдельные карточки
товара, не 1 с 6 вариантами). Поэтому сидинг — строго "только если товара
с таким именем ещё нет вообще"; если есть хотя бы один — ничего не трогаем
и не создаём, чтобы не плодить дубли поверх уже введённых вручную данных.
"""

from django.db import migrations


def seed(apps, schema_editor):
    ProductCategory = apps.get_model('lors', 'ProductCategory')
    Product = apps.get_model('lors', 'Product')
    ProductVariant = apps.get_model('lors', 'ProductVariant')
    Color = apps.get_model('lors', 'Color')

    PRODUCT_NAME = 'طقم منظم صندوق LORS ديلوكس'
    if Product.objects.filter(name=PRODUCT_NAME).exists():
        return

    category, _ = ProductCategory.objects.get_or_create(name='إكسسوارات', defaults={'order': 0})
    product = Product.objects.create(
        name=PRODUCT_NAME, category=category, description='', is_active=True,
    )

    for order, (name, hex_code) in enumerate([('بني', '#6F4E37'), ('أسود', '#000000')]):
        color, _ = Color.objects.get_or_create(name=name, defaults={'hex_code': hex_code, 'order': 100 + order})
        ProductVariant.objects.get_or_create(
            product=product, color=color, defaults={'price': 45, 'is_active': True, 'order': order},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0023_carmodel_cascade_fields_remove_package_dese'),
    ]

    operations = [
        migrations.RunPython(seed, noop),
    ]
