# Generated by Django 6.0.6
"""
Первый реальный товар вне калькулятора коврика: органайзер багажника «LORS
Deluxe» — по фото/цене, которые прислал заказчик (طقم منظم صندوق LORS
ديلوكس, $45, коричневый/чёрный). Намеренно не связан с калькулятором
коврика (Lead.car_model/material/...) — отдельная линейка товаров,
заказ через product_variant (TYPE_PRODUCT_ORDER), см. Lead в models.py.

Фото вариантов не заведено — залить через инлайн на карточке товара в
/admin/, как только будут реальные файлы.
"""

from django.db import migrations


def seed(apps, schema_editor):
    ProductCategory = apps.get_model('lors', 'ProductCategory')
    Product = apps.get_model('lors', 'Product')
    ProductVariant = apps.get_model('lors', 'ProductVariant')
    Color = apps.get_model('lors', 'Color')

    category, _ = ProductCategory.objects.get_or_create(name='إكسسوارات', defaults={'order': 0})
    product, _ = Product.objects.get_or_create(
        name='طقم منظم صندوق LORS ديلوكس',
        defaults={'category': category, 'description': '', 'is_active': True},
    )

    for order, (name, hex_code) in enumerate([('بني', '#6F4E37'), ('أسود', '#000000')]):
        color, _ = Color.objects.get_or_create(name=name, defaults={'hex_code': hex_code, 'order': 100 + order})
        ProductVariant.objects.get_or_create(
            product=product, color=color, defaults={'price': 45, 'is_active': True, 'order': order},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0023_carmodel_cascade_fields_remove_package_dese'),
    ]

    operations = [
        migrations.RunPython(seed, noop),
    ]
