# Generated by Django 6.0.6 on 2026-08-15 09:57
"""
Отмена 0023 в части package/dese: заказчик прислал реальный, актуальный
прайс-лист (гуглотаблица «أسعار مفارش LORS»), где чёрным по белому —
«كل أنواع الباكاج» (доплата за любой тип пакета) $35, логотип обычный/
королевский $3/$6, дэсе тип 1/2 $15/$10, отдельными платными строками.
Утверждение «пакетов не существует» из прошлого разговора было ошибочным
(путаница между Lead.has_package — эта доплата — и CarModel.package —
количеством ковриков в комплекте конкретной модели, это разные вещи под
похожим названием). Восстанавливаю Lead.has_package/dese и модели
DeseOption/PricingSettings, с теми же значениями, что были: LogoOption
(3/6, не удалялся) — уже на месте.

Заодно поправляю название категории Carnival+Staria+H1 — в реальном
прайсе она «Carnival + Staria + Service + H1» (сегмент «سرفيس» пропущен
при первом сидировании в 0020).
"""

from django.db import migrations, models
import django.db.models.deletion


DESE_OPTIONS = [
    ('Тип 1', 15),
    ('Тип 2', 10),
]


def seed(apps, schema_editor):
    DeseOption = apps.get_model('lors', 'DeseOption')
    PricingSettings = apps.get_model('lors', 'PricingSettings')
    PriceCategory = apps.get_model('lors', 'PriceCategory')

    for order, (name, price) in enumerate(DESE_OPTIONS):
        DeseOption.objects.get_or_create(name=name, defaults={'price': price, 'order': order})
    PricingSettings.objects.get_or_create(pk=1, defaults={'package_price': 35})

    PriceCategory.objects.filter(name='Carnival + Staria + H1 (с пакетом)').update(
        name='Carnival + Staria + Service + H1 (с пакетом)',
    )


def unseed(apps, schema_editor):
    PriceCategory = apps.get_model('lors', 'PriceCategory')
    PriceCategory.objects.filter(name='Carnival + Staria + Service + H1 (с пакетом)').update(
        name='Carnival + Staria + H1 (с пакетом)',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0024_seed_lors_deluxe_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'вариант дэсе',
                'verbose_name_plural': 'варианты дэсе',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.DecimalField(decimal_places=2, default=35, max_digits=10, verbose_name='цена добавления пакета')),
            ],
            options={
                'verbose_name': 'настройки цен',
                'verbose_name_plural': 'настройки цен',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='has_package',
            field=models.BooleanField(default=False, verbose_name='добавить пакет'),
        ),
        migrations.AddField(
            model_name='lead',
            name='dese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='lors.deseoption'),
        ),
        migrations.RunPython(seed, unseed),
    ]
