# Generated by Django 6.0.6
"""
Заказчик прислал единый утверждённый прайс-лист компании («Просьба строго
придерживаться указанных цен в соответствии с утверждённым регламентом
компании») — все суммы совпадают один в один с тем, что уже было в базе
(включая доплату за пакет $35, логотипы $3/$6, дэсе $15/$10 из 0025), цены
не меняю. Меняю только названия 12 `PriceCategory` на официальную
формулировку из документа (была самодеятельная — "Седан, 5 мест (с
пакетом)" и т.п.) и название логотипа "Королевский" на официальное
"Malaki" (в документе — «Премиальный логотип «Malaki»», собственное имя,
не перевожу).
"""

from django.db import migrations

# (старое название, новое официальное название, цена — для сверки при откате)
PRICE_CATEGORY_RENAMES = [
    ('Седан, 5 мест (с пакетом)', '5-местный седан'),
    ('Джип, 5 мест (с пакетом)', '5-местный джип / SUV'),
    ('7 мест (с пакетом)', '7-местный автомобиль'),
    ('7 мест, бизнес (с пакетом)', '7-местный автомобиль бизнес-класса'),
    ('Американец — Cadillac, GMC и т.п. (с пакетом)', 'Американские автомобили: Cadillac, GMC и т. п.'),
    ('Carnival + Staria + Service + H1 (с пакетом)', 'H1 + Carnival + Staria + микроавтобусы/сервисные авто'),
    ('Американец в целом + Land Cruiser (с пакетом)', 'Американские автомобили в целом + Land Cruiser'),
    ('Седан (без пакета)', 'Седан без багажника'),
    ('Джип (без пакета)', 'Джип / SUV без багажника'),
    ('7 мест, без 7-го ряда (без пакета)', '7-местный автомобиль без багажника и без ковриков 3-го ряда'),
    ('7 мест, с 7-м рядом (без пакета)', '7-местный автомобиль без багажника, но с ковриками 3-го ряда'),
    ('Бизнес (без пакета)', 'Автомобиль бизнес-класса без багажника'),
]


def rename(apps, schema_editor):
    PriceCategory = apps.get_model('lors', 'PriceCategory')
    LogoOption = apps.get_model('lors', 'LogoOption')

    for old_name, new_name in PRICE_CATEGORY_RENAMES:
        PriceCategory.objects.filter(name=old_name).update(name=new_name)
    LogoOption.objects.filter(name='Королевский').update(name='Malaki')


def unrename(apps, schema_editor):
    PriceCategory = apps.get_model('lors', 'PriceCategory')
    LogoOption = apps.get_model('lors', 'LogoOption')

    for old_name, new_name in PRICE_CATEGORY_RENAMES:
        PriceCategory.objects.filter(name=new_name).update(name=old_name)
    LogoOption.objects.filter(name='Malaki').update(name='Королевский')


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0025_restore_package_dese_fix_carnival_category'),
    ]

    operations = [
        migrations.RunPython(rename, unrename),
    ]
