# Generated by Django 6.0.6 on 2026-08-15 10:22
"""
Косметика, схему не меняет: verbose_name у Lead.has_package/
PricingSettings.package_price говорил "пакет" — по голосовым от заказчика
выяснилось, что это неверный перевод «الباكاج» (в оригинале про багажник,
доплата за коврик в багажник, а не общий "пакет опций"), сотрудники в
/admin/ на этом путались. Имена полей (has_package/package_price) не
трогаю — это внутренние идентификаторы, менять руками через несколько
миграций/фронт лишний риск ради косметики; человекочитаемые подписи
поправлены на "багажник".
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0026_official_price_list_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='has_package',
            field=models.BooleanField(default=False, verbose_name='добавить багажник'),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='package_price',
            field=models.DecimalField(decimal_places=2, default=35, max_digits=10, verbose_name='цена добавления багажника'),
        ),
    ]
