# Generated by Django 6.0.6 on 2026-08-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0027_verbose_name_bagazhnik_not_paket'),
    ]

    operations = [
        migrations.AddField(
            model_name='logooption',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_options', to='lors.brand'),
        ),
    ]
