# Generated by Django 6.0.6
"""
Данные из МойСклад (склад комплектующих цеха, снят 2026-08-15) — токен и
доступ у заказчика, цены на комплектующие там не выставлены (это не прайс,
а учёт сырья), поэтому цены здесь берутся из уже известного прайс-листа
(логотип обычный $3 / Malaki $6), а не из МойСклад.

## Цвета (`Color`)

В МойСклад товары `eva лист <цвет>` (полотно EVA, из чего кроят коврик) и
`подпятник <тип> <цвет>` вместе дают палитру реальных цветов — гораздо
шире, чем два цвета (بني/أسود), что были в базе раньше. Оба товарных ряда
используют, по сути, одну и ту же турецкую цветовую номенклатуру (koyu
kahve / acik kahve и "eva лист"-варианты "Bunni Ghomik (Kahve)" / "Malyaki
(Acik Taba)" — это те же тёмно-/светло-коричневый, только с опечатками у
кладовщика при вводе) — здесь они сведены в одну палитру.
HEX подобраны на глаз под название, не завод-эталон — поправить в /admin/,
если у реального материала другой оттенок.

## Логотипы по маркам (`LogoOption.brand`)

В МойСклад шильдик логотипа заведён отдельной позицией на каждую марку
("Toyota (logo maliki)", "BMW (logo maliki)" и т.п. — 51 марка, плюс те же
марки без "(logo maliki)" — обычный вариант) — то есть маркам реально
соответствуют разные физические шильдики, а не один и тот же "логотип"
на любую машину, как было в `LogoOption` до этой миграции.

Сопоставление названий из МойСклад с `Brand` — по нормализованному имени
(без пробелов/дефисов/регистра), с точечными синонимами (Mazerati ->
Maserati, опечатка в источнике; Volks Wagen -> Volkswagen; Mercedes Benz ->
mercedes-Benz). Из 51 марки МойСклад совпало 41 — 10 не сопоставлены,
ничего для них не создаётся:
- AMG, BRABUS — это суббренды/тюнинг-ателье Mercedes, не отдельная марка в
  каталоге (`CarModel` заведён под "Mercedes-Benz", не под "AMG"/"Brabus").
- CHRYSLER, CITROEN, IVECO, Mini — реальные марки авто, но их вообще нет в
  `Brand` (в каталоге колёс/лекал таких моделей не заведено) — не мой
  масштаб решать, заводить ли новую марку в каталог; логотип под них можно
  добавить, как только появится сама марка.
- M-logo, R-logo, S-logo — не марки, похоже на внутренний код кладовщика
  (возможно шильдики без опознавательной надписи бренда) — не расшифровал,
  не завожу вслепую.
- Prado — это модель (Land Cruiser Prado), не марка — уже покрывается
  логотипом марки Toyota.

Существующие 2 записи `LogoOption` без марки (id 1 "Обычный", id 2
"Malaki") не трогаю — остаются универсальным вариантом для марок без
своего шильдика (39 из 70 марок каталога, которых нет в списке МойСклад,
и 10 несопоставленных выше).
"""

from django.db import migrations

NEW_COLORS = [
    # (название, hex)
    ('أبيض', '#FFFFFF'),           # Beyaz — белый
    ('رمادي', '#8A8A8A'),          # Gri — серый
    ('رمادي غامق', '#4A4A4A'),     # Koyu gri — тёмно-серый
    ('بيج', '#E3D5B3'),            # Bej — бежевый
    ('خمري', '#6D071A'),           # Bordo — бордовый
    ('أحمر', '#D32F2F'),           # Kırmızı — красный
    ('برتقالي', '#F5811F'),        # Turuncu — оранжевый
    ('كحلي', '#1B2A4A'),           # Lacivert — тёмно-синий (navy)
    ('أزرق', '#1E5AA8'),           # Mavi — синий
    ('وردي', '#E85D9E'),           # Pembe — розовый
    ('بني فاتح', '#A97C50'),       # Açık Kahve / Malyaki (Acik Taba) — светло-коричневый
]

# (название в МойСклад, точное имя в нашей Brand)
BRAND_MATCHES = [
    ('Audi', 'Audi'), ('BYD', 'BYD'), ('Cadillac', 'Cadillac'), ('Chery', 'Chery'),
    ('Chevrolet', 'Chevrolet'), ('DACIA', 'Dacia'), ('DODGE', 'Dodge'), ('FAW', 'FAW'),
    ('FORD', 'FORD'), ('Fiat', 'Fiat'), ('GMC', 'GMC'), ('Geely', 'Geely'),
    ('Genesis', 'Genesis'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('ISUZU', 'Isuzu'),
    ('JAECOO', 'Jaecoo'), ('JAGUAR', 'Jaguar'), ('Jeep', 'Jeep'), ('Jetour', 'Jetour'),
    ('KIA', 'Kia'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('MAYBACH', 'Maybach'),
    ('MAZDA', 'Mazda'), ('MG', 'MG'), ('Mazerati', 'Maserati'), ('Mercedes Benz', 'mercedes-Benz'),
    ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('OPEL', 'Opel'), ('Porsche', 'Porsche'),
    ('Renault', 'Renault'), ('Skoda', 'Skoda'), ('SsangYong', 'SsangYong'), ('Suzuki', 'Suzuki'),
    ('Toyota', 'Toyota'), ('Volks Wagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('bmw', 'BMW'),
    ('infiniti', 'Infiniti'),
]

LOGO_STYLES = [
    ('Обычный', 3),
    ('Malaki', 6),
]


def seed(apps, schema_editor):
    Color = apps.get_model('lors', 'Color')
    Brand = apps.get_model('lors', 'Brand')
    LogoOption = apps.get_model('lors', 'LogoOption')

    for order, (name, hex_code) in enumerate(NEW_COLORS):
        Color.objects.get_or_create(name=name, defaults={'hex_code': hex_code, 'order': 200 + order})

    for _ms_name, brand_name in BRAND_MATCHES:
        brand = Brand.objects.filter(name=brand_name).first()
        if not brand:
            continue
        for order, (style_name, price) in enumerate(LOGO_STYLES):
            LogoOption.objects.get_or_create(
                brand=brand, name=style_name, defaults={'price': price, 'order': order},
            )


def unseed(apps, schema_editor):
    Color = apps.get_model('lors', 'Color')
    LogoOption = apps.get_model('lors', 'LogoOption')

    Color.objects.filter(name__in=[n for n, _ in NEW_COLORS]).delete()
    LogoOption.objects.filter(brand__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0028_logooption_brand'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
