# Generated by Django 6.0.8
"""
LogoOption.name/DeseOption.name показывались клиенту по-русски ("Обычный",
"Тип 1" и т.п.) на арабоязычном сайте — тот же класс бага, что и
body_variant (см. 0577e205 / parse_car_models). Переводит на арабский.

Заодно унифицирует расхождение в названиях +6$ надбавки: универсальная
запись называлась "Премиальный «Malaki»" (переименована вручную раньше),
40 записей по маркам (0029_moysklad_colors_and_brand_logos) — просто
"Malaki". Обе становятся "ملكي" (собственно то, что "Malaki" и значит —
транслитерация обратно в арабицу, не бренд-решение).
"""

from django.db import migrations

RENAMES = [
    ('lors', 'LogoOption', 'Обычный', 'عادي'),
    ('lors', 'LogoOption', 'Malaki', 'ملكي'),
    ('lors', 'LogoOption', 'Премиальный «Malaki»', 'ملكي'),
    ('lors', 'DeseOption', 'Тип 1', 'نوع 1'),
    ('lors', 'DeseOption', 'Тип 2', 'نوع 2'),
]


def translate(apps, schema_editor):
    for app_label, model_name, old_name, new_name in RENAMES:
        Model = apps.get_model(app_label, model_name)
        Model.objects.filter(name=old_name).update(name=new_name)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0029_moysklad_colors_and_brand_logos'),
    ]

    operations = [
        migrations.RunPython(translate, noop),
    ]
