# Generated by Django 6.0.8 on 2026-09-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0030_translate_logo_dese_names_to_arabic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_type',
            field=models.CharField(blank=True, choices=[('تكسي عادي', 'تكسي عادي'), ('خمس أبواب (هاش باك)', 'خمس أبواب (هاش باك)'), ('ثلاث أبواب (هاش باك)', 'ثلاث أبواب (هاش باك)'), ('بابين (كوبي)', 'بابين (كوبي)'), ('كوبي بابين', 'كوبي بابين'), ('اربع ابواب (كوبي)', 'اربع ابواب (كوبي)'), ('بيك آب', 'بيك آب'), ('شاحنة', 'شاحنة'), ('باكاج طويل', 'باكاج طويل')], max_length=255, verbose_name='тип автомобиля'),
        ),
    ]
