# Generated by Django 6.0.8
"""
46 моделей (пикапы и грузовики/фургоны) были без price_category — в
официальном прайс-листе для них отдельного тарифа не было. Ahmad задал
плоские цены: пикап 100$, грузовик 190$ — заводит 2 новые ценовые
категории и распределяет по ним модели (по sheet_row — устойчивее id
между окружениями, см. 0030).

Заодно проставляет car_type ('بيك آب'/'شاحنة' — второй только что добавлен
в CAR_TYPE_CHOICES, см. 0031) там, где он ещё не был задан вручную — если
уже стоял (7 моделей из 46, включая одну "تكسي عادي" — DFSK, явно не
пикап/грузовик, см. коммит), не трогает.

DFSK "(2025) gorly 600" (sheet_row=229) сознательно исключён из обеих
групп — car_type у неё уже "تكسي عادي" (обычное такси), судя по notes
("7+7 мест") это не пикап и не грузовик, а что-то вроде микроавтобуса.
Цену для неё нужно решать отдельно.
"""

from django.db import migrations

PICKUP_SHEET_ROWS = [
    226, 225, 244, 245, 260, 257, 258, 259, 265, 263, 264, 462, 672, 673,
    796, 818, 815, 816, 817, 814, 865, 866, 964, 965, 1048, 1049, 1050,
    1080, 1090, 1091,
]

TRUCK_SHEET_ROWS = [
    166, 261, 495, 690, 695, 694, 693, 789, 787, 788, 790, 811, 1102, 1121, 1162,
]

PICKUP_CAR_TYPE = 'بيك آب'
TRUCK_CAR_TYPE = 'شاحنة'


def assign(apps, schema_editor):
    PriceCategory = apps.get_model('lors', 'PriceCategory')
    CarModel = apps.get_model('lors', 'CarModel')

    pickup_cat, _ = PriceCategory.objects.get_or_create(
        name='Пикап', defaults={'price': 100, 'order': 12},
    )
    truck_cat, _ = PriceCategory.objects.get_or_create(
        name='Грузовик', defaults={'price': 190, 'order': 13},
    )

    for sheet_row in PICKUP_SHEET_ROWS:
        cm = CarModel.objects.filter(sheet_row=sheet_row).first()
        if not cm:
            continue
        cm.price_category = pickup_cat
        if not cm.car_type:
            cm.car_type = PICKUP_CAR_TYPE
        cm.save(update_fields=['price_category', 'car_type'])

    for sheet_row in TRUCK_SHEET_ROWS:
        cm = CarModel.objects.filter(sheet_row=sheet_row).first()
        if not cm:
            continue
        cm.price_category = truck_cat
        if not cm.car_type:
            cm.car_type = TRUCK_CAR_TYPE
        cm.save(update_fields=['price_category', 'car_type'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lors', '0031_add_truck_car_type'),
    ]

    operations = [
        migrations.RunPython(assign, noop),
    ]
